"$schema" = 'https://starship.rs/config-schema.json'

format = """
$time$cmd_duration $status
[](fg:#1A3356)\
$directory\
[](fg:#1A3356 bg:#4A3A0A)\
$git_branch\
$git_status\
[ ](fg:#4A3A0A)\
"""

# Disable the blank line at the start of the prompt
 add_newline = false

[status]
style = 'fg:red'
symbol = '❌ '
success_symbol = '[✔](green)'
format = '[$symbol$common_meaning$signal_name$maybe_int]($style) '
map_symbol = true
disabled = false 
 
[cmd_duration]
min_time = 500
show_milliseconds = true
style = "bg:#033500 fg:#85a16a"
format = '[⏱ $duration]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#033500 fg:#85a16a"
format = '[➠ $time ]($style)'

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '

[directory]
style = "fg:#D6E8FF bold bg:#1A3356"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = " 󰈙 "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important 󰈙 " = " 󰈙 "

[git_branch]
symbol = ""
style = "fg:#F5D06A bold bg:#4A3A0A"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "fg:#F5D06A bold bg:#4A3A0A"
format = '[$all_status$ahead_behind ]($style)'


